name: goal_conditioned_rl2
channels:
  - conda-forge
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - greenlet=3.0.3
  - ipdb=0.13.13
  - ipython=8.20.0
  - jedi=0.19.1
  - libcxx=16.0.6
  - libffi=3.4.2
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - msgpack-python=1.0.7
  - ncurses=6.4
  - neovim=0.3.1
  - openssl=3.2.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - prompt-toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pynvim=0.5.0
  - python=3.10.13
  - python_abi=3.10
  - readline=8.2
  - setuptools=69.0.3
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - toml=0.10.2
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - unidecode=1.3.8
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - chex==0.1.85
      - click==8.1.7
      - cloudpickle==3.0.0
      - distrax==0.1.5
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.6.0
      - farama-notifications==0.0.4
      - flax==0.8.0
      - fsspec==2023.12.2
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.41
      - glfw==2.6.5
      - gymnasium==0.29.1
      - gymnasium-robotics==1.2.4
      - hydra-core==1.3.2
      - idna==3.6
      - imageio==2.33.1
      - importlib-resources==6.1.1
      - jax==0.4.23
      - jaxlib==0.4.23
      - jinja2==3.1.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpi4jax==0.4.0.post3
      - mpi4py==3.1.5
      - mujoco==2.3.7
      - nest-asyncio==1.6.0
      - numpy==1.26.3
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - optax==0.1.8
      - orbax-checkpoint==0.5.2
      - packaging==23.2
      - pettingzoo==1.24.3
      - pillow==10.2.0
      - protobuf==4.25.2
      - psutil==5.9.8
      - pyopengl==3.1.7
      - pyyaml==6.0.1
      - requests==2.31.0
      - rich==13.7.0
      - scipy==1.12.0
      - sentry-sdk==1.40.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tensorflow-probability==0.23.0
      - tensorstore==0.1.52
      - toolz==0.12.1
      - urllib3==2.2.0
      - wandb==0.16.2
      - zipp==3.17.0
